- name: 'get existing rails server pid'
  command: cat {{ base_foreman_directory }}tmp/pids/server.pid
  register: existing_rails_server
  become_user: vagrant
  ignore_errors: True
  delegate_to: "{{ capsule_server }}"

- name: 'check for rails server'
  fail: msg="No rails server detected running on {{ capsule_server }},
             please run `rails s` on {{ capsule_server }}"
  when: existing_rails_server.rc != 0

- name: 'Add group foreman'
  group: name=foreman state=present
  delegate_to: "{{ capsule_server }}"

- name: 'Install foreman-installer-katello'
  yum: name="foreman-installer-katello"
  delegate_to: "{{ capsule_server }}"
