---
- include: devel_install.yml
  when: (capsule_upgrade == False and devel is defined and devel == True)

- include: install.yml
  when: capsule_upgrade == False

- include: upgrade.yml
  when: capsule_upgrade == True
