---
- name: 'Install dependencies'
  become: true
  yum: name=bzip2,gcc,openssl-devel,readline-devel,zlib-devel state=present

- name: 'Clone rbenv'
  git: repo=https://github.com/rbenv/rbenv.git dest=~/.rbenv

- name: 'Compile dynamic bash extension'
  command: 'cd ~/.rbenv && src/configure && make -C src'

- name: 'Add rbenv to PATH'
  lineinfile: dest=~/.bash_profile line='export PATH="$HOME/.rbenv/bin:$PATH"'

- name: 'Initialize rbenv on login'
  lineinfile: dest=~/.bash_profile line="eval \"$(rbenv init -)\""

- name: 'Reload the environment'
  shell: 'source ~/.bash_profile'

- name: 'Clone ruby-build'
  git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: 'Build and install ruby'
  command: ~/.rbenv/bin/rbenv install {{ hammer_devel_ruby_version }} creates=~/.rbenv/versions/{{ hammer_devel_ruby_version }}

- name: 'Set global ruby version'
  command: ~/.rbenv/bin/rbenv global {{ hammer_devel_ruby_version }}
