---
hammer_devel_ruby_version: 2.3.1
hammer_devel_host: http://centos7-devel.example.com:3000
hammer_devel_username: admin
hammer_devel_password: changeme
hammer_devel_repositories:
  - theforeman/hammer-cli
  - theforeman/hammer-cli-foreman
  - theforeman/hammer-cli-foreman-tasks
  - katello/hammer-cli-csv
  - katello/hammer-cli-katello
