---
- hosts: server capsule
  become: true
  vars:
    capsule_server_group: "server-{{ inventory_hostname }}"
    capsule_server: "{{ groups[capsule_server_group][0] }}"
  roles:
    - foreman_repositories
    - katello_repositories
    - etc_hosts
    - {role: capsule, foreman_directory: '/home/vagrant/foreman/config/', 
       devel: True, base_foreman_directory: '/home/vagrant/foreman/'}
