- hosts: all
  vars:
    katello_version: 3.1
    foreman_version: 1.12
    katello_installer_command: >
      foreman-installer -v
      --scenario katello
      --enable-foreman-plugin-discovery
      --enable-foreman-plugin-bootdisk
      --enable-foreman-plugin-remote-execution
      --enable-foreman-plugin-hooks
      --enable-foreman-plugin-openscap
      --enable-foreman-proxy-plugin-openscap
      --enable-foreman-proxy-plugin-remote-execution-ssh
  roles:
    - etc_hosts
    - foreman_repositories
    - katello_repositories
    - katello
